#!/bin/bash

HERE=$(dirname "${BASH_SOURCE}")


. "${HERE}/core/cli.sh"

. "${HERE}/commands/default.sh"
. "${HERE}/commands/version.sh"
. "${HERE}/commands/help.sh"
. "${HERE}/commands/setup.sh"
. "${HERE}/commands/master.sh"
. "${HERE}/commands/join.sh"
. "${HERE}/commands/bootstrap.sh"



# Dispatch the arguments
dispatch op "$@"
